backend:
  name: github
  repo: 1halfplusminus/gatsby-cms
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: "src/blogs"
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }